name = "489785334ffc8b837e1a3af9a33c73213459a751"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_VERSION = "22.16.0"
